version: "3"

services:
  postgres:
    image: postgis/postgis:13-3.0-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
    # restart: always
    ports:
      - 5432:5432
  caddy:
    image: caddy:2-alpine
    # restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 80:80
  imgproxy:
    image: darthsim/imgproxy:v2
    environment:
      IMGPROXY_KEY:
      IMGPROXY_SALT:
      IMGPROXY_ALLOWED_SOURCES:
    ports:
      - 8080:8080

volumes:
  pgdata:
