name: mix

on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test

    services:
      postgres:
        image: postgis/postgis:16-3.4-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - id: versions
        uses: marocchino/tool-versions-action@v1

      - uses: erlef/setup-beam@v1
        with:
          elixir-version: 1.17
          otp-version: 27

      - uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: test-${{ github.head_ref || github.ref }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            test-${{ github.head_ref || github.ref }}-mix-
            test-refs/heads/master-mix-

      - run: mix deps.get --only test
      - run: mix compile --warnings-as-errors
      - run: mix format --check-formatted
      - run: mix test --include integration
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          APP_STORE_KEY_ID: ${{ secrets.APP_STORE_KEY_ID }}
          APP_STORE_KEY: ${{ secrets.APP_STORE_KEY }}
          APP_STORE_ISSUER_ID: ${{ secrets.APP_STORE_ISSUER_ID }}
          APNS_TOPIC: ${{ secrets.APNS_TOPIC }}
