name: mix

on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v4

      - id: versions
        uses: marocchino/tool-versions-action@v1

      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ steps.versions.outputs.elixir }}
          otp-version: ${{ steps.versions.outputs.erlang }}

      - uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: test-otp-${{ steps.versions.outputs.erlang }}-elixir-${{ steps.versions.outputs.elixir }}-ref-${{ github.head_ref || github.ref }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            test-otp-${{ steps.versions.outputs.erlang }}-elixir-${{ steps.versions.outputs.elixir }}-ref-${{ github.head_ref || github.ref }}-mix-
            test-otp-${{ steps.versions.outputs.erlang }}-elixir-${{ steps.versions.outputs.elixir }}-ref-refs/heads/master-mix-

      - run: mix deps.get --only test
      - run: mix compile --warnings-as-errors
      - run: mix format --check-formatted
      - run: mix test --include integration
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          APP_STORE_KEY_ID: ${{ secrets.APP_STORE_KEY_ID }}
          APP_STORE_KEY: ${{ secrets.APP_STORE_KEY }}
          APP_STORE_ISSUER_ID: ${{ secrets.APP_STORE_ISSUER_ID }}
          APNS_TOPIC: ${{ secrets.APNS_TOPIC }}
